</html>
<head>
	<title>Welcome to webserv!</title>
	<style>
		body {
			width: 80em;
			margin: 0 auto;
		}
	</style>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>

<body class="success">
	<h1>Welcome to Webserv!</h1>
	<p>If you see this page, then everything works correctly!</p>
	<img src="images/8.ico">
	<!-- <a href="/autoindex">Checking the autoindex</a> -->
	<a href="/authorization_page">Checking the authorization operation</a>
	<a href="/user_registration">Checking the operation of the PHP script</a>
	<p>Designed by <ap href="https://profile.intra.42.fr/users/sjolynn"> Sjolynn </ap> & <ap
			href="https://profile.intra.42.fr/users/hrema">Hrema</ap> & <ap
			href="https://profile.intra.42.fr/users/anatashi">Anatashi</a></p>
</body>

</html>
<ul>